####################################
# Author: Veronika Klazova
# Description: Automated Grafana Login with default creentials using Selenium and Python
# Code generated by Selenium Web IDE and adjustments by Veronika Klauzova
####################################

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.service import Service

class TestGrafanaautologin():
  def setup_method(self, method):
    path="/usr/bin/chromedriver"
    service = Service(path)
    self.driver = webdriver.Chrome(service=service)
    self.driver.implicitly_wait(5) # seconds
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_grafanaautologin(self):
    self.driver.get("http://localhost:3000/login")
# 2 | setWindowSize | 1265x720 | 
    self.driver.set_window_size(1265, 720)
    # 3 | type | id=:r0: | admin
    self.driver.find_element(By.XPATH, "/html/body/div/div[1]/div/main/div/div/div[3]/div/div/div[2]/div/div/form/div[1]/div[2]/div/div/div/input").send_keys("admin")
    # 4 | click | id=:r1: | 
    self.driver.find_element(By.XPATH, "/html/body/div/div[1]/div/main/div/div/div[3]/div/div/div[2]/div/div/form/div[2]/div[2]/div/div/div/input").click()
    # 5 | type | id=:r1: | admin
    self.driver.find_element(By.XPATH, "/html/body/div/div[1]/div/main/div/div/div[3]/div/div/div[2]/div/div/form/div[2]/div[2]/div/div/div/input").send_keys("admin")
    # 6 | click | css=.css-1b7vft8-button | 
    self.driver.find_element(By.XPATH, "/html/body/div/div[1]/div/main/div/div/div[3]/div/div/div[2]/div/div/form/button").click()
    self.driver.find_element(By.XPATH, "/html/body/div/div[1]/div/main/div/div/div[3]/div/div/div[2]/div/form/div[4]/div[2]/button").click()
    time.sleep(10)


testClass = TestGrafanaautologin()
testClass.setup_method("")
testClass.test_grafanaautologin()
testClass.teardown_method("")
